// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as AskWarCouncilProcedure from "../ask_war_council_procedure";

export type AskWarCouncilArgs = __Infer<typeof AskWarCouncilProcedure.params>;
export type AskWarCouncilResult = __Infer<typeof AskWarCouncilProcedure.returnType>;

