// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CancelOrderReducer from "../cancel_order_reducer";
import ConfigureWarCouncilReducer from "../configure_war_council_reducer";
import DeployBlockadeReducer from "../deploy_blockade_reducer";
import JoinArenaReducer from "../join_arena_reducer";
import MoveUnitReducer from "../move_unit_reducer";
import PlaceOrderReducer from "../place_order_reducer";
import RecordWarCounselReducer from "../record_war_counsel_reducer";

export type CancelOrderParams = __Infer<typeof CancelOrderReducer>;
export type ConfigureWarCouncilParams = __Infer<typeof ConfigureWarCouncilReducer>;
export type DeployBlockadeParams = __Infer<typeof DeployBlockadeReducer>;
export type JoinArenaParams = __Infer<typeof JoinArenaReducer>;
export type MoveUnitParams = __Infer<typeof MoveUnitReducer>;
export type PlaceOrderParams = __Infer<typeof PlaceOrderReducer>;
export type RecordWarCounselParams = __Infer<typeof RecordWarCounselReducer>;

