// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  botId: __t.u32().primaryKey().name("bot_id"),
  callsign: __t.string(),
  faction: __t.string(),
  strategy: __t.string(),
  objective: __t.string(),
  targetNodeId: __t.u32().name("target_node_id"),
  confidence: __t.u32(),
  reasoning: __t.string(),
  updatedAt: __t.timestamp().name("updated_at"),
});
