// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  tick: __t.u64(),
  telemetrySequence: __t.u64().name("telemetry_sequence"),
  tradeSequence: __t.u64().name("trade_sequence"),
  totalOperations: __t.u64().name("total_operations"),
  activeBots: __t.u32().name("active_bots"),
  season: __t.string(),
  lastEnergyPrice: __t.u32().name("last_energy_price"),
  lastMatterPrice: __t.u32().name("last_matter_price"),
  lastDataPrice: __t.u32().name("last_data_price"),
  startedAt: __t.timestamp().name("started_at"),
});
