// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  x: __t.u32(),
  y: __t.u32(),
  resource: __t.string(),
  yieldRate: __t.u32().name("yield_rate"),
  controller: __t.string(),
  controllingPlayer: __t.option(__t.identity()).name("controlling_player"),
  defense: __t.u32(),
  blockadeUntilMicros: __t.u64().name("blockade_until_micros"),
  pressure: __t.u32(),
});
