// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  sequence: __t.u64().primaryKey(),
  operation: __t.string(),
  actor: __t.string(),
  rowsTouched: __t.u32().name("rows_touched"),
  wasmTransitions: __t.u32().name("wasm_transitions"),
  shadowHops: __t.u32().name("shadow_hops"),
  shadowEstimatedMicros: __t.u32().name("shadow_estimated_micros"),
  committedAt: __t.timestamp().name("committed_at"),
});
