// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AgentIntent = __t.object("AgentIntent", {
  botId: __t.u32(),
  callsign: __t.string(),
  faction: __t.string(),
  strategy: __t.string(),
  objective: __t.string(),
  targetNodeId: __t.u32(),
  confidence: __t.u32(),
  reasoning: __t.string(),
  updatedAt: __t.timestamp(),
});
export type AgentIntent = __Infer<typeof AgentIntent>;

export const AiConfig = __t.object("AiConfig", {
  id: __t.u32(),
  apiKey: __t.string(),
  model: __t.string(),
});
export type AiConfig = __Infer<typeof AiConfig>;

export const ArenaState = __t.object("ArenaState", {
  id: __t.u32(),
  tick: __t.u64(),
  telemetrySequence: __t.u64(),
  tradeSequence: __t.u64(),
  totalOperations: __t.u64(),
  activeBots: __t.u32(),
  season: __t.string(),
  lastEnergyPrice: __t.u32(),
  lastMatterPrice: __t.u32(),
  lastDataPrice: __t.u32(),
  startedAt: __t.timestamp(),
});
export type ArenaState = __Infer<typeof ArenaState>;

export const Blockade = __t.object("Blockade", {
  id: __t.u64(),
  nodeId: __t.u32(),
  owner: __t.identity(),
  faction: __t.string(),
  expiresAtMicros: __t.u64(),
  strength: __t.u32(),
});
export type Blockade = __Infer<typeof Blockade>;

export const BotAgent = __t.object("BotAgent", {
  id: __t.u32(),
  name: __t.string(),
  faction: __t.string(),
  credits: __t.u64(),
  energy: __t.u64(),
  matter: __t.u64(),
  data: __t.u64(),
  aggression: __t.u32(),
});
export type BotAgent = __Infer<typeof BotAgent>;

export const CounselResult = __t.object("CounselResult", {
  objective: __t.string(),
  rationale: __t.string(),
  risk: __t.string(),
  recommendedAction: __t.string(),
  targetNodeId: __t.u32(),
  model: __t.string(),
  mode: __t.string(),
});
export type CounselResult = __Infer<typeof CounselResult>;

export const GridNode = __t.object("GridNode", {
  id: __t.u32(),
  x: __t.u32(),
  y: __t.u32(),
  resource: __t.string(),
  yieldRate: __t.u32(),
  controller: __t.string(),
  controllingPlayer: __t.option(__t.identity()),
  defense: __t.u32(),
  blockadeUntilMicros: __t.u64(),
  pressure: __t.u32(),
});
export type GridNode = __Infer<typeof GridNode>;

export const OrderBook = __t.object("OrderBook", {
  id: __t.u64(),
  owner: __t.identity(),
  ownerName: __t.string(),
  faction: __t.string(),
  side: __t.string(),
  asset: __t.string(),
  price: __t.u32(),
  remaining: __t.u32(),
  createdAt: __t.timestamp(),
});
export type OrderBook = __Infer<typeof OrderBook>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  faction: __t.string(),
  credits: __t.u64(),
  energy: __t.u64(),
  matter: __t.u64(),
  data: __t.u64(),
  score: __t.u64(),
  online: __t.bool(),
  joinedAt: __t.timestamp(),
});
export type Player = __Infer<typeof Player>;

export const TelemetryLog = __t.object("TelemetryLog", {
  sequence: __t.u64(),
  operation: __t.string(),
  actor: __t.string(),
  rowsTouched: __t.u32(),
  wasmTransitions: __t.u32(),
  shadowHops: __t.u32(),
  shadowEstimatedMicros: __t.u32(),
  committedAt: __t.timestamp(),
});
export type TelemetryLog = __Infer<typeof TelemetryLog>;

export const Trade = __t.object("Trade", {
  id: __t.u64(),
  sequence: __t.u64(),
  asset: __t.string(),
  price: __t.u32(),
  volume: __t.u32(),
  buyer: __t.string(),
  seller: __t.string(),
  executedAt: __t.timestamp(),
});
export type Trade = __Infer<typeof Trade>;

export const Unit = __t.object("Unit", {
  id: __t.u64(),
  owner: __t.option(__t.identity()),
  botId: __t.u32(),
  callsign: __t.string(),
  faction: __t.string(),
  x: __t.u32(),
  y: __t.u32(),
  power: __t.u32(),
  bot: __t.bool(),
  lastActionTick: __t.u64(),
});
export type Unit = __Infer<typeof Unit>;

export const WarCounsel = __t.object("WarCounsel", {
  id: __t.u64(),
  commander: __t.identity(),
  commanderName: __t.string(),
  faction: __t.string(),
  objective: __t.string(),
  rationale: __t.string(),
  risk: __t.string(),
  recommendedAction: __t.string(),
  targetNodeId: __t.u32(),
  model: __t.string(),
  createdAt: __t.timestamp(),
});
export type WarCounsel = __Infer<typeof WarCounsel>;

export const WorldTimer = __t.object("WorldTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type WorldTimer = __Infer<typeof WorldTimer>;

