// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  owner: __t.option(__t.identity()),
  botId: __t.u32().name("bot_id"),
  callsign: __t.string(),
  faction: __t.string(),
  x: __t.u32(),
  y: __t.u32(),
  power: __t.u32(),
  bot: __t.bool(),
  lastActionTick: __t.u64().name("last_action_tick"),
});
