// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  commander: __t.identity(),
  commanderName: __t.string().name("commander_name"),
  faction: __t.string(),
  objective: __t.string(),
  rationale: __t.string(),
  risk: __t.string(),
  recommendedAction: __t.string().name("recommended_action"),
  targetNodeId: __t.u32().name("target_node_id"),
  model: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
